global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.44.234:9090','172.31.32.29:9100','172.31.45.118:9100','172.31.44.226:9100']
